WORK_DIR=$(pwd)
LLVM_DIR=$WORK_DIR/llvm
BUILD_LLVM_DIR=$LLVM_DIR/build-llvm
LLVM_SOURCE_DIR=$LLVM_DIR/llvm-project

mkdir -p $BUILD_LLVM_DIR
cd $BUILD_LLVM_DIR
cmake $LLVM_SOURCE_DIR/llvm -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -G Ninja \
    -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_USE_LINKER=mold \
    -DLLVM_ENABLE_ASSERTIONS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_ENABLE_WARNINGS=OFF -DLLVM_APPEND_VC_REV=OFF -DLLVM_TARGETS_TO_BUILD="LoongArch" \
    -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
    -DLLVM_FORCE_ENABLE_STATS=ON
ninja
