name: "Issue Ops"

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  checks: read
  contents: read 

jobs:
  opt-cov-ts:
    runs-on: self-hosted
    steps:
      - uses: github/command@v2.0.0
        id: pr
        with:
          command: "pr"
          allowed_contexts: "issue"
          allowlist: "llvm/pr-subscribers-loongarch"
          allowlist_pat: ${{ secrets.ALLOWLIST_PAT }}
      - name: pr
        if: ${{ steps.command.outputs.continue == 'true' }}
        run: |
          echo "params: ${{ steps.command.outputs.params }}"